remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Dunnatello's Portfolio
show_downloads: false
markdown: GFM
#baseurl: ""
url: "https://dunnatello.github.io"

collections:
  docs:
    output: true
    source: docs


